# Generated by Django 3.2.13 on 2022-05-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onscreen",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=32,
            ),
        ),
    ]
